# Generated by Django 4.2.21 on 2025-06-04 00:51

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Başlangıç Zamanı')),
                ('status', models.CharField(choices=[('running', 'Çalışıyor'), ('completed_analysis', 'Tamamlandı (Analiz Edildi)'), ('completed_insufficient_points', 'Tamamlandı (Yetersiz Nokta)'), ('interrupted_ctrl_c', 'Durduruldu (Ctrl+C)'), ('error_in_loop', 'Hata Oluştu')], default='running', max_length=50, verbose_name='Tarama Durumu')),
                ('start_angle_setting', models.FloatField(verbose_name='Ayar: Başlangıç Açısı')),
                ('end_angle_setting', models.FloatField(verbose_name='Ayar: Bitiş Açısı')),
                ('step_angle_setting', models.FloatField(verbose_name='Ayar: Adım Açısı')),
                ('buzzer_distance_setting', models.IntegerField(verbose_name='Ayar: Uyarı Mesafesi (cm)')),
                ('invert_motor_direction_setting', models.BooleanField(default=False, verbose_name='Ayar: Motor Yönü Ters')),
                ('calculated_area_cm2', models.FloatField(blank=True, null=True, verbose_name='Hesaplanan Alan (cm²)')),
                ('perimeter_cm', models.FloatField(blank=True, null=True, verbose_name='Çevre (cm)')),
                ('max_width_cm', models.FloatField(blank=True, null=True, verbose_name='Maksimum Genişlik (cm)')),
                ('max_depth_cm', models.FloatField(blank=True, null=True, verbose_name='Maksimum Derinlik (cm)')),
                ('ai_commentary', models.TextField(blank=True, null=True, verbose_name='Yapay Zeka Yorumu')),
            ],
            options={
                'verbose_name': 'Tarama Kaydı',
                'verbose_name_plural': 'Tarama Kayıtları',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='ScanPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('derece', models.FloatField(verbose_name='Açı (°)')),
                ('mesafe_cm', models.FloatField(verbose_name='Mesafe (cm)')),
                ('hiz_cm_s', models.FloatField(default=0, verbose_name='Hız (cm/s)')),
                ('timestamp', models.DateTimeField(verbose_name='Zaman Damgası')),
                ('x_cm', models.FloatField(verbose_name='X Koordinatı (cm)')),
                ('y_cm', models.FloatField(verbose_name='Y Koordinatı (cm)')),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='scanner.scan', verbose_name='Ait Olduğu Tarama')),
            ],
            options={
                'verbose_name': 'Tarama Noktası',
                'verbose_name_plural': 'Tarama Noktaları',
                'ordering': ['timestamp'],
            },
        ),
    ]
